title: ShuHao's Space 
page-top-title: Shu Hao
top-section-bg-text: Blockchain and Distributed Computing
home-subtitle: Shu Hao&ensp;|&ensp;熊书豪
copyright-text: '&copy; Shu Hao2024-2025. All Rights Reserved.'
